paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos disponibles
      tags:
        - Products
      responses:
        "201":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos, se retorna arreglo con los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/product"
        "500":
          description: "Error interno del servidor, usualmente generado por una query  defectuosa o un fallo de conexion con la base de datos"

  /api/products/{pid}:
    get:
      summary: Obtiene el producto solicitado por id
      tags:
        - Products
      paramemeters:
      name: pid
      in: path
      required: true
      desription: El id del producto se debe ingresar
      schema:
        $type: String
      responses:
        "201":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos, se retorna arreglo con los productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/product"
        "500":
          description: "Error interno del servidor, usualmente generado por una query  defectuosa o un fallo de conexion con la base de datos"

components:
  schemas:
    product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo.
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad de stock del producto
        category:
          type: String
          description: A que categoria corresponde el producto
        img:
          type: String
          description: Imagen representativa del producto
        owner:
          type: User ObjectId
          description: Role de usuario que creo el producto
      example:
        _id: ObjectId("654076edce44cbffed1e95a6")
        title: Dulce de Leche
        description: La serenisima
        price: 950
        stock: 21
        category: Alimentos
        img: /img/sprite.jpg
        role: Admin
