paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos disponibles.
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos, se retorna arreglo con los productos
        "400"
          description: Se nvio un dato no esperado
        "500":
          description: "Error interno del servidor, usualmente generado por una query  defectuosa o un fallo de conexion con la base de datos"
